[
{"id":"5","content":"武器装备保障标准化、信息化专项工作","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"0","depth":"1"},
{"id":"5.1","content":"集团公司武器装备综合保障标准体系及编制计划","completeFormal":"报告","completeDate":"2017.1","personLiable":"","company":"","remark":"","parent":"5","depth":"2"},
{"id":"5.3","content":"完成S系列标准及北约编码体系的翻译与转化","completeFormal":"标准","completeDate":"2017.8","personLiable":"丁泉","company":"","remark":"","parent":"5","depth":"2"},
{"id":"","content":"ASD SX000i S系列标准使用指南 翻译","completeFormal":"标准","completeDate":"2017.3","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"ASD S2000M（6.0版）装备管理综合数据处理国际规范翻译","completeFormal":"标准","completeDate":"2017.4","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"ASD S4000P（1.0版）定期维修分析过程国际通用手册翻译","completeFormal":"标准","completeDate":"2017.5","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"ASD S5000F （1.0版）使用与维修数据反馈国际通用应用手册翻译","completeFormal":"标准","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"ASD SX001G系列综合后勤保障规范词汇表翻译","completeFormal":"标准","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"北约体系 ACODP-1 北约编码手册翻译","completeFormal":"标准","completeDate":"2017.6","personLiable":"丁泉","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"北约体系 ACODP-2 北约供应品手册（对应美军标H2）翻译","completeFormal":"标准","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"北约体系 ACODP-3 核准物资名称目录（对应美军标H6）翻译","completeFormal":"标准","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"北约体系 标准名称AIN 翻译（47256×2项<br />北约体系 口语名翻译（31952×2项<br />北约体系 图纸备注翻译（208964项<br />北约体系 MRC翻译（27423项<br />北约体系 MRD翻译（151807项<br />北约体系 ISAC翻译（31410项）","completeFormal":"上线","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"","content":"北约体系 标准名称AIN 校准发<br />北约体系 口语名翻译校准发<br />北约体系 图纸备注翻译校准发<br />北约体系 MRC翻译校准发<br />北约体系 MRD翻译校准发<br />北约体系 ISAC翻译校准发布","completeFormal":"上线","completeDate":"2017.11","personLiable":"","company":"","remark":"","parent":"5.3","depth":"3"},
{"id":"5.4","content":"集团公司武器装备综合保障标准编制","completeFormal":"标准","completeDate":"2017.12","personLiable":"王  伟","company":"","remark":"","parent":"5","depth":"2"},
{"id":"5.4.2","content":"●军贸型号物品分类规<br />●军贸型号物品标准名称规<br />●军贸型号物品标准名称规范","completeFormal":"标准","completeDate":"2017.11","personLiable":"丁泉","company":"","remark":"","parent":"5.4","depth":"3"},
{"id":"5.4.4","content":"●结构划分编码要求（S1000<br />●基本元素设计、编辑管理要求（S1000<br />●结构划分编码要求（S1000<br />●数据模块设计管理要求（S1000<br />●数据模块设计管理要求（S1000<br />●出版物设计、编制、发布管理（S1000<br />●样式要求（S1000）","completeFormal":"标准","completeDate":"2017.11","personLiable":"","company":"航天测控","remark":"","parent":"5.4","depth":"3"},
{"id":"","content":"●武器装备综合保障规范使用指<br />●初始供应清单数据规<br />●备件供应清单数据规<br />●订单管理数据规范","completeFormal":"标准","completeDate":"2017.11","personLiable":"丁泉","company":"","remark":"","parent":"5.4.4","depth":"4"},
{"id":"","content":"●物品编码及认证业务规<br />●物品编码及认证实施指<br />●物品识别与编码标<br />●物品识别与编码数据字典","completeFormal":"标准","completeDate":"2017.11","personLiable":"","company":"310所","remark":"","parent":"5.4.4","depth":"4"},
{"id":"","content":"●保障性分析标准（S3000L<br />●计划性维修标准（S4000P<br />●保障数据反馈标准（S5000F）","completeFormal":"标准","completeDate":"2017.12","personLiable":"丁泉","company":"","remark":"","parent":"5.4.4","depth":"4"},
{"id":"5.5","content":"综合保障信息化平台建设","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"5","depth":"2"},
{"id":"5.5.1","content":"完成集团公司“专有云”二期建设武器装备保障专区V2.0上线部署和原型项目（2000等）试点应用；集团公司专家组工作计划上线运行","completeFormal":"软件、数据","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.5","depth":"3"},
{"id":"5.5.1.1","content":"物项编码认证管理模块","completeFormal":"","completeDate":"","personLiable":"刘运峰","company":"","remark":"","parent":"5.5.1","depth":"4"},
{"id":"","content":"需求分析<br />●北约数据新数据快速导入、集团物项认证需求、物项信息综合查询<br />●集团物品主数据与北约标准体系转换模型","completeFormal":"报告","completeDate":"2017.3","personLiable":"刘运峰","company":"","remark":"","parent":"5.5.1.1","depth":"5"},
{"id":"","content":"软件开发","completeFormal":"上线","completeDate":"2017.6","personLiable":"资小军","company":"","remark":"","parent":"5.5.1.1","depth":"5"},
{"id":"","content":"推广应用<br />●集团物资部数据转化与编码认证；<br />●2000型号数据转化与编码认证； ","completeFormal":"上线","completeDate":"","personLiable":"刘运峰","company":"","remark":"","parent":"5.5.1.1","depth":"5"},
{"id":"5.5.1.2","content":"公共数据源管理（含公共管理）模块","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"5.5.1","depth":"4"},
{"id":"","content":"需求分<br />●计划管理模型及流程需求<br />●型号产品履约和服役阶段技术状态管理模型（含技术状态库、基线、产品等相关模型<br /> ●构型库编码设计（含SNS编码）<br />●产品图解零部件目录模型<br />●CSDB（公共数据源）管理模型（包含对与综合保障有关的文档、资料、数据等的管理）；","completeFormal":"需求分<br />报告","completeDate":"2017.<br />2017.<br /><br />2017.<br />2017.<br />2017.5","personLiable":"方赤峰","company":"","remark":"","parent":"5.5.1.2","depth":"5"},
{"id":"","content":"软件开发","completeFormal":"上线","completeDate":"2017.6","personLiable":"资小军","company":"","remark":"","parent":"5.5.1.2","depth":"5"},
{"id":"","content":"推广应<br />●12个型号货架产品库、基线产品库建立 ","completeFormal":"上线","completeDate":"2017.<br />2017.1","personLiable":"方赤峰","company":"","remark":"","parent":"5.5.1.2","depth":"5"},
{"id":"5.5.1.3","content":"交互式电子手册管理模块","completeFormal":"","completeDate":"","personLiable":"刘运峰","company":"航天测<br />二院X型号两总","remark":"","parent":"5.5.1","depth":"4"},
{"id":"","content":"需求分析?","completeFormal":"报告","completeDate":"2017.3","personLiable":"","company":"","remark":"","parent":"5.5.1.3","depth":"5"},
{"id":"","content":"软件开<br />●IETM创编端集成上<br />●IETM CSDB集成上<br />●IETM浏览端持续改<br />","completeFormal":"上线","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.5.1.3","depth":"5"},
{"id":"","content":"推广应<br />●1401型号应用；<br />●FD2000型号应用； ","completeFormal":"上线","completeDate":"","personLiable":"","company":"","remark":"","parent":"5.5.1.3","depth":"5"},
{"id":"5.5.1.4","content":"供货管理模块","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"5.5.1","depth":"4"},
{"id":"","content":"需求分<br />●集团现有履约合同涉及军贸型号的交付物收集与分析<br />●结合S2000M整理交付物并进行WBS分解<br />●合同管理、军贸产品计划管理、采购与交付管理、备附件管理功能需求；","completeFormal":"报告","completeDate":"2017.<br /><br />2017.<br />2017.4","personLiable":"聂文琪","company":"华腾业务部","remark":"","parent":"5.5.1.4","depth":"5"},
{"id":"","content":"软件开发","completeFormal":"上线","completeDate":"2017.6","personLiable":"资小军","company":"","remark":"","parent":"5.5.1.4","depth":"5"},
{"id":"","content":"推广应<br />●集团军贸履约项目供应管理","completeFormal":"上线","completeDate":"2017.6","personLiable":"聂文琪","company":"","remark":"","parent":"5.5.1.4","depth":"5"},
{"id":"5.5.1.5","content":"售后服务管理/快速响应管理模块","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"5.5.1","depth":"4"},
{"id":"","content":"需求分<br />●在役技术状态管理模型；<br />●重大任务保障、大/中/小修、预防性巡检、故障件返修等保障业务需求；<br />●全资可视化看板需求； ","completeFormal":"报告","completeDate":"2017.<br />2017.<br /><br />2017.12","personLiable":"<br />方赤<br />方赤<br /><br />郑开<br />","company":"","remark":"","parent":"5.5.1.5","depth":"5"},
{"id":"5.5.1.6","content":"“专栏专区”模块","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"5.5.1","depth":"4"},
{"id":"","content":"需求分<br />计划管理、交流讨论、信息发<br />标准查询、成果展示","completeFormal":"报告","completeDate":"2017.6","personLiable":"聂文琪","company":"二院二部","remark":"","parent":"5.5.1.6","depth":"5"},
{"id":"","content":"软件开<br />专家组/专业组2017年计划管理","completeFormal":"上线","completeDate":"2017.6","personLiable":"资小军","company":"","remark":"","parent":"5.5.1.6","depth":"5"},
{"id":"5.5.2","content":"开展武器装备保障平台军贸保障快响研究，进一步完善武器装备综合保障信息化平台总体架构设计","completeFormal":"报告","completeDate":"2017.9","personLiable":"郑开原","company":"二院二部","remark":"","parent":"5.5","depth":"3"},
{"id":"5.5.3","content":"结合“专有云”三期建设，开展武器装备保障专区新功能模块论证及立项","completeFormal":"报告","completeDate":"2017.1","personLiable":"方赤<br />郑开原","company":"","remark":"","parent":"5.5","depth":"3"},
{"id":"","content":"“专有云”三期需求分析","completeFormal":"评审结论","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"5.5.3","depth":"4"},
{"id":"","content":"“专有云”三期详细设计","completeFormal":"评审结论","completeDate":"2017.7","personLiable":"","company":"","remark":"","parent":"5.5.3","depth":"4"},
{"id":"5.5.4","content":"依次开展二期建设武器装备保障专区军贸型号项目和国内型号项目推广应用","completeFormal":"报告","completeDate":"2017.12","personLiable":"郑开原","company":"华腾公司、  <br />二院、三院、四院、十院","remark":"","parent":"5.5","depth":"3"},
{"id":"5.6","content":"组织审查“武器装备保障标准化、信息化专项工作”各节点交付物","completeFormal":"会议纪要","completeDate":"2017.12","personLiable":"","company":"","remark":"","parent":"5","depth":"2"},
{"id":"","content":"S系列标准翻译交付物审<br />SX000i，S2000翻译交付物审<br />S4000P，S5000F翻译交付物审<br />STEI00、SX001GS翻译交付物审查","completeFormal":"评审意见","completeDate":"<br />2017.<br />2017.<br />2017.8","personLiable":"丁泉","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"","content":"北约编码体系的翻译交付物评<br />北约体系 标准名称AIN、MR C第一批翻译交付物审<br />北约体系 标准名称AIN、MR C第二批翻译交付物审<br />ACODP-1 北约编码手册翻译交付物审查","completeFormal":"评审意见","completeDate":"<br />2017.<br />2017.<br />2017.7","personLiable":"丁泉","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"","content":"军贸型号物品分类规范、军贸型号物品标准名称规范、军贸型号物品标准名称规范","completeFormal":"评审意见","completeDate":"2017.11","personLiable":"丁泉","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"","content":"武器装备保障专区 供应管理模块详细设计评审","completeFormal":"评审意见","completeDate":"2017.4","personLiable":"聂文琪","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"","content":"武器装备保障专区三期需求评审","completeFormal":"评审意见","completeDate":"2017.6","personLiable":"方赤峰","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"","content":"武器装备保障专区三期详细设计评审","completeFormal":"评审意见","completeDate":"2017.8","personLiable":"方赤峰","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"","content":"武器装备保障专区“专栏专区”模块需求评审","completeFormal":"评审意见","completeDate":"2017.8","personLiable":"聂文琪","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"","content":"北约物品编码技术研究与应用（含自主创新项目和军贸基金项目<br />●项目开题、中期、结题审查<br />●集团主数据、指定型号数据北约编码转化交付物审查","completeFormal":"评审意见","completeDate":"<br /><br />2017.1<br />","personLiable":"刘运峰","company":"","remark":"","parent":"5.6","depth":"3"},
{"id":"6","content":"课题研究","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"0","depth":"1"},
{"id":"6.1.2","content":"北约物品编码技术研究与应用","completeFormal":"报告","completeDate":"2017.12","personLiable":"","company":"","remark":"","parent":"6","depth":"2"},
{"id":"","content":"北约编码数据转换","completeFormal":"文件、软件、数据","completeDate":"2017.3","personLiable":"刘运峰","company":"","remark":"","parent":"6.1.2","depth":"3"},
{"id":"","content":"分类对标","completeFormal":"文件、数据","completeDate":"2017.4","personLiable":"刘运峰","company":"","remark":"","parent":"6.1.2","depth":"3"},
{"id":"","content":"文件翻译","completeFormal":"文件","completeDate":"2017.8","personLiable":"丁泉","company":"","remark":"","parent":"6.1.2","depth":"3"},
{"id":"","content":"数据及文件翻译","completeFormal":"数据","completeDate":"2017.8","personLiable":"丁泉","company":"","remark":"","parent":"6.1.2","depth":"3"},
{"id":"","content":"物品编码认证系统","completeFormal":"软件","completeDate":"2017.1","personLiable":"刘运峰","company":"","remark":"","parent":"6.1.2","depth":"3"},
{"id":"","content":"发布集团标准","completeFormal":"文件","completeDate":"2017.12","personLiable":"丁泉","company":"","remark":"","parent":"6.1.2","depth":"3"},
{"id":"","content":"集成演示系统","completeFormal":"数据","completeDate":"2017.12","personLiable":"刘运峰","company":"","remark":"","parent":"6.1.2","depth":"3"},
{"id":"6.1.3","content":"武器装备综合保障信息化平台构建技术研究","completeFormal":"报告","completeDate":"2017.12","personLiable":"郑开原","company":"","remark":"","parent":"6","depth":"2"},
{"id":"","content":"综保平台功能架构研究","completeFormal":"","completeDate":"2017.12","personLiable":"","company":"","remark":"","parent":"6.1.3","depth":"3"},
{"id":"","content":"综保平台WBS数据模型构建技术研究","completeFormal":"","completeDate":"2017.12","personLiable":"","company":"","remark":"","parent":"6.1.3","depth":"3"},
{"id":"9","content":"人才培养","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"0","depth":"1"},
{"id":"9.2","content":"制作S系列标准、综合保障“平台”培训课件","completeFormal":"课件","completeDate":"2017.6","personLiable":"","company":"","remark":"","parent":"9","depth":"2"},
{"id":"","content":"SX000i培训教程编制","completeFormal":"","completeDate":"","personLiable":"郑开原","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"北约编码培训教程编制","completeFormal":"","completeDate":"","personLiable":"刘运峰","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"S1000D培训教程编制","completeFormal":"","completeDate":"","personLiable":"方赤峰","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"S2000M培训教程编制","completeFormal":"","completeDate":"","personLiable":"聂文琪","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"S3000L培训教程编制","completeFormal":"","completeDate":"","personLiable":"刘运峰","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"S4000P培训教程编制","completeFormal":"","completeDate":"","personLiable":"丁  泉","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"S5000F培训教程编制","completeFormal":"","completeDate":"","personLiable":"郑开原","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"平台培训教程编制","completeFormal":"","completeDate":"","personLiable":"刘运峰","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"","content":"使用维护说明编制","completeFormal":"","completeDate":"","personLiable":"资小军","company":"","remark":"","parent":"9.2","depth":"3"},
{"id":"9.3","content":"开展面向中心、分中心的综合保障技术体系、标准体系、综合保障“平台”等通用专业知识培训","completeFormal":"培训记录","completeDate":"2017.6","personLiable":"郑开原","company":"集团科研部","remark":"","parent":"9","depth":"2"},
{"id":"10","content":"组织机构设立相关工作","completeFormal":"","completeDate":"","personLiable":"","company":"","remark":"","parent":"0","depth":"1"},
{"id":"10.1","content":"上报军贸分中心组建方案","completeFormal":"会议纪要","completeDate":"2017.3","personLiable":"聂文琪","company":"中心","remark":"","parent":"10","depth":"2"},
{"id":"10.3","content":"军贸分中心召开启动会","completeFormal":"纪要","completeDate":"2017.4","personLiable":"聂文琪","company":"中心","remark":"","parent":"10","depth":"2"},
{"id":"10.4","content":"军贸分中心年度工作总结","completeFormal":"纪要","completeDate":"2017.12","personLiable":"聂文琪","company":"","remark":"","parent":"10","depth":"2"}
]
